---
show_calculations: false

# One side value
# Could be overriden per room
height_clearance: 10
# One side value
# Could be overriden per room
length_clearance: 10

# Could be overriden per room
min_last_row_height: 60.0
# Could be overriden per room
desired_last_row_height: 100.0
# Could be overriden per room, in %/100
cover_margin: 0.05

# Optional: use it if you want to limit calculation to only selected floor type
# Otherwise leparquet will use all floors
# floor_index: 1
# Tool cut width for short cuts in mm
lateral_tool_cut_width: 2.0
# Tool cut width for longitudinal cuts in mm
longitudinal_tool_cut_width: 3.0

# Type of laylout: 1/2 - brick, 1/3 - deck, free-joints, fixed-joints
# This is global or override per room
# layout:
#   type: 1/2
#   first_board: "1/2" # or "full"

layout:
  type: 1/3
  first_board: "1/3" # or "full"

# layout:
#   type: free-joints
#   first_board: "full"

# layout:
#   type: fixed-joints
#   first_board: "full"

rooms:
  - name: "small"
    size:
      height: 2110
      width: 3800

    cover_margin: 0.1
    first_board: "1/3" # "full", "1/3", "2/3"

  - name: "big"
    size:
      height: 3800
      width: 14010

    first_board: "1/3" # "full", "1/3", "2/3"

    # height_clearance
    # length_clearance
    # min_last_row_height: 60.0
    # desired_last_row_height: 100.0
    # cover_margin: 0.05

floor_choices:
  -
     type: "151L8AEK09KW220"
     name: "European Naturals Collection"
     board_size:
       height: 187
       width: 2266

     pack_area: 2.54
     boards_per_pack: 6
     price_per_msq: 719

  -
    type: "Timberwise"
    type: "Timberwise-Ek"
    board_size:
      height: 185
      width: 2180

    # Optional
    pack_area: 2.42
    # boards_per_pack optional, calculated as nearest integer using board area and pack area
    boards_per_pack: 6

    # Optional
    price_per_msq: 1150 # any currency
    # Optional
    # pack_weight: 21 # kg

  -
    type: "7876069T-#1"
    name: "L2000"
    board_size:
      height: 162
      width: 2000

    pack_area: 1.94
    boards_per_pack: 6
    price_per_msq: 699

  -
    type: "7876069T-#2"
    name: "L2200"
    board_size:
      height: 162
      width: 2200

    pack_area: 2.14
    boards_per_pack: 6
    price_per_msq: 699

  -
     type: "151L8AEK1DKW240"
     name: "Classic Nouveau Collection"
     board_size:
       height: 187
       width: 2420

     pack_area: 2.72
     boards_per_pack: 6
     price_per_msq: 780
