---
show_calculations: false

# One side value
height_clearance: 10
# One side value
length_clearance: 10

# Could be override per room
min_last_row_height: 60.0
# Could be override per room
desired_last_row_height: 100.0
# Could be override per room, in %/100
cover_margin: 0.05
# Optinal: use it if you want to limit calculation to only selected floor type
# Otherwise leparquet will use all floors
floor_index: 0
# Tool cut width in mm
tool_cut_width: 2.0
# Type of laylout: 1/2 - brick, 1/3 - deck, rests
#layout_runout: 1/3

rooms:
  # - name: "small"
  #   size:
  #     height: 2110
  #     width: 3800

  #   cover_margin: 0.1
  #   first_board: "1/3" # "full", "1/3", "2/3"

  - name: "big"
    size:
      height: 3800
      width: 14010

    first_board: "1/3" # "full", "1/3", "2/3"

    # height_clearance
    # min_last_row_height: 60.0
    # desired_last_row_height: 100.0
    # cover_margin: 0.05

floor_choices:
  -
     type: "Kärs 151L8AEK09KW220"
     board_size:
       height: 187
       width: 2200

     pack_area: 2.54
     boards_per_pack: 6

  -
    type: "Timberwise-185 Ek"
    board_size:
      height: 185
      width: 2180

    pack_area: 2.42
    # boards_per_pack optional, calculated as nearest integer using board area and pack area
    boards_per_pack: 6

  -
    type: "7876069T #1"
    board_size:
      height: 162
      width: 2000

    pack_area: 1.94
    boards_per_pack: 6

  -
    type: "7876069T #2"
    board_size:
      height: 162
      width: 2200

    pack_area: 2.14
    boards_per_pack: 6

  -
     type: "Kärs 151L8AEK1DKW240"
     board_size:
       height: 187
       width: 2420

     pack_area: 2.72
     boards_per_pack: 6

