---
# Set this to true to see how LeParquet does it's calculations
show_calculations: false

# Amount of clearance to take into consider when laying out boards.
# This value is for one side. Taken into account on top/bottom edges.
# Could be overriden per room
height_clearance: 10
# Same as above but for the last and right sides
# Could be overriden per room
width_clearance: 10

# Minimum amoung of last boards height in mm. Usually it must be > 60mm
# Could be overriden per room
min_last_row_height: 60.0
# You could specify last row (the one at the bottom of the room) board height in mm.
# Could be overriden per room
desired_last_row_height: 100.0
# This is not usind in layout computation.
# Specify how large area overhead you expect per room to compare it with reality.
# Could be overriden per room, in %/100
cover_margin: 0.05

# Optional: use it if you want to limit calculation to only selected floor type
# This is zero-based index of the floor in floor array
# If commented then leparquet will use all floors
#floor_index: 1

# Tool cut width for short cuts in mm. Max 5mm
lateral_tool_cut_width: 2.0
# Tool cut width for longitudinal cuts in mm. Max 5mm
longitudinal_tool_cut_width: 3.0

# Type of laylout: 1/2 - brick, 1/3 - deck, free-joints, fixed-joints
# This is global, but you can override it per room
layout:
  type: deck
  first_board: 1/3 # or "full"

# layout:
#   type: deck
#   first_board: "1/3" # or "full"

# layout:
#   type: free-joints
#   first_board: "full"

# layout:
#   type: fixed-joints
#   first_board: "full"

# Array of rooms you would like to calculate layout for
rooms:
  - name: "small"  # Room name to identify it later
    size:
      # Room height in mm (from top to bottom, measured between walls)
      height: 2110
      # Room width  in mm (from left to right (layout direction), measured between walls)
      width: 3800

    # Cover margin override for this room
    cover_margin: 0.1
    # Length (width) of thefFirst board in the first row
    # Valid value: "full", "1/3", "2/3"
    first_board: 1/3

    # doors array is optional,
    # Doors must not intersect
    # Door rect is measure from the wall where it starts. See measurements section in README.md
    doors:
      - edge: left # left, right, top, bottom
        displacement: 170 # (0, 0) top, left
        name: door1 # name used to identify the door
        size:
          height: 35 # Size in mm
          width: 900 # Size in mm


  - name: "big"
    size:
      height: 3800
      width: 14010

    first_board: "1/3" # "full", "1/3", "2/3"

    # This is override for this room
    height_clearance: 200
    # This is override for this room
    width_clearance: 300
    # This is override for this room
    min_last_row_height: 100.0
    # This is override for this room
    desired_last_row_height: 140.0
    # This is override for this room
    cover_margin: 0.15

# Array of possible floor types used for layout
floor_choices:
  -
    type: "151L8AEK1DKW240" # Type, usually Art#
    name: "Classic Nouveau Collection" # Name
    board_size: # Board size as specified by the vendor
      height: 187 # Size in mm
      width: 2420 # Size in mm

    # Optional: If known specify it so that Leparquet can tell you how many packs to buy
    # Usually you take this from floor TDS
    # Value in m^2
    pack_area: 2.72

    # Optional: If known specify it so that Leparquet can tell you how many packs to buy
    # Usually you take this from floor TDS
    # Value in items per pack
    boards_per_pack: 6

    # If known used to calculate BOM per room
    price_per_msq: 780
