---
show_calculations: true

# One side value
height_clearance: 10
# One side value
length_clearance: 10

# Could be override per room
min_last_row_height: 60.0
# Could be override per room
desired_last_row_height: 100.0
# Could be override per room, in %/100
cover_margin: 0.05

rooms:
  - name: "small"
    size:
      height: 2110
      width: 3800

    cover_margin: 0.1
    first_board: "full" # "full", "1/3", "2/3"

  - name: "big"
    size:
      height: 3800
      width: 14010

    first_board: "third" # "full", "1/3", "2/3"

    # min_last_row_height: 60.0
    # desired_last_row_height: 100.0
    # cover_margin: 0.05

floor_choices:
  -
    type: "1"
    board_size:
      height: 190
      width: 1900

    pack_area: 2.7
    # boards_per_pack optional, calculated as nearest integer using board area and pack area
    boards_per_pack: 6

  -
    type: "2"
    board_size:
      height: 190
      width: 1900

    pack_area: 2.7
    # boards_per_pack optional, calculated as nearest integer using board area and pack area
    boards_per_pack: 6

# self.board_length = 1818.0
# self.board_length = 2000.0
# self.board_length = 2080.0
# self.board_length = 2180.0
# self.board_height = 185.0
# self.pack_area_m2 = 2.42

# self.board_length = 2200.0
# self.board_height = 207
# self.pack_area_m2 = 3.18

# 151XCDEKFZKW195
# self.board_length = 1900.
# self.board_height = 190.
# self.pack_area_m2 = 2.17

# 151L8AEK09KW220
#self.board_length = 2266.
#self.board_height = 187.
#self.pack_area_m2 = 2.5
