---
show_calculations: false

# One side value
# Could be overriden per room
height_clearance: 10
# One side value
# Could be overriden per room
length_clearance: 10

# Could be overriden per room
min_last_row_height: 60.0
# Could be overriden per room
desired_last_row_height: 100.0
# Could be overriden per room, in %/100
cover_margin: 0.05

# Optional: use it if you want to limit calculation to only selected floor type
# Otherwise leparquet will use all floors
# floor_index: 1
# Tool cut width for short cuts in mm
lateral_tool_cut_width: 2.0
# Tool cut width for longitudinal cuts in mm
longitudinal_tool_cut_width: 3.0

# Type of laylout: 1/2 - brick, 1/3 - deck, free-joints, fixed-joints
# This is global, but you can override it per room
# layout:
#   type: 1/2
#   first_board: "1/2" # or "full"

layout:
  type: 1/3
  first_board: "1/3" # or "full"

# layout:
#   type: free-joints
#   first_board: "full"

# layout:
#   type: fixed-joints
#   first_board: "full"

rooms:
  - name: "small"
    size:
      height: 2110
      width: 3800

    cover_margin: 0.1
    first_board: 1/3 # "full", "1/3", "2/3"

    # doors array is optional, TODO: doors intersections
    # door rect is measure from the wall where it starts
    doors:
      - edge: left # left, right, top, bottom
        displacement: 170 # (0, 0) top, left
        name: door1
        size:
          height: 35
          width: 900

      - edge: left # left, right, top, bottom
        displacement: 1270 # (0, 0) top, left, is from the wall
        name: door2
        size:
          height: 50
          width: 500
    
      - edge: top # left, right, top, bottom
        displacement: 70 # (0, 0) top, left
        name: door3
        size:
          height: 40
          width: 900
          
      - edge: bottom # left, right, top, bottom
        displacement: 2830 # (0, 0) top, left
        name: door4
        size:
          height: 180
          width: 900

      - edge: right # left, right, top, bottom
        displacement: 200 # (0, 0) top, left
        name: door5
        size:
          height: 0
          width: 900


  # - name: "big"
  #   size:
  #     height: 3800
  #     width: 14010

  #   first_board: "1/3" # "full", "1/3", "2/3"

#    height_clearance: 200
#    length_clearance: 300
    # min_last_row_height: 60.0
    # desired_last_row_height: 100.0
    # cover_margin: 0.05

floor_choices:
  -
     type: "151L8AEK1DKW240"
     name: "Classic Nouveau Collection"
     board_size:
       height: 187
       width: 2420

     pack_area: 2.72
     boards_per_pack: 6
     price_per_msq: 780
